<?php
/**
 * Autogenerated by Thrift Compiler (0.7.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
namespace psdshow\scribe_thrift\thrift\scribe;

use Thrift\Type\TType;

$GLOBALS['E_ResultCode'] = array(
  'OK' => 0,
  'TRY_LATER' => 1,
);

final class ResultCode {
  const OK = 0;
  const TRY_LATER = 1;
  static public $__names = array(
    0 => 'OK',
    1 => 'TRY_LATER',
  );
}