<?php
/**
 * Autogenerated by Thrift Compiler (0.7.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */

namespace psdshow\scribe_thrift\thrift\scribe;

use psdshow\scribe_thrift\thrift\fb303\FacebookServiceIf;
use psdshow\scribe_thrift\thrift\fb303\FacebookServiceClient;

use Thrift\Protocol\TProtocol;
use Thrift\Type\TMessageType;
use Thrift\Exception\TApplicationException;


interface scribeIf extends FacebookServiceIf {
  public function Log($messages);
}


class scribeClient extends FacebookServiceClient implements scribeIf {
  public function __construct($input, $output=null) {
    parent::__construct($input, $output);
  }

  public function Log($messages)
  {
    $this->send_Log($messages);
    return $this->recv_Log();
  }

  public function send_Log($messages)
  {
    $args = new scribe_Log_args();
    $args->messages = $messages;
    $bin_accel = function_exists('thrift_protocol_write_binary') && ($this->output_ instanceof TProtocol::$TBINARYPROTOCOLACCELERATED);
    if ($bin_accel)
    {
      thrift_protocol_write_binary($this->output_, 'Log', TMessageType::CALL, $args, $this->seqid_, $this->output_->isStrictWrite());
    }
    else
    {
      $this->output_->writeMessageBegin('Log', TMessageType::CALL, $this->seqid_);
      $args->write($this->output_);
      $this->output_->writeMessageEnd();
      $this->output_->getTransport()->flush();
    }
  }

  public function recv_Log()
  {
    $bin_accel = function_exists('thrift_protocol_read_binary') && ($this->input_ instanceof TProtocol::$TBINARYPROTOCOLACCELERATED);
    if ($bin_accel) $result = thrift_protocol_read_binary($this->input_, 'scribe_Log_result', $this->input_->isStrictRead());
    else
    {
      $rseqid = 0;
      $fname = null;
      $mtype = 0;

      $this->input_->readMessageBegin($fname, $mtype, $rseqid);
      if ($mtype == TMessageType::EXCEPTION) {
        $x = new TApplicationException();
        $x->read($this->input_);
        $this->input_->readMessageEnd();
        throw $x;
      }
      $result = new scribe_Log_result();
      $result->read($this->input_);
      $this->input_->readMessageEnd();
    }
    if ($result->success !== null) {
      return $result->success;
    }
    throw new Exception("Log failed: unknown result");
  }

}